### ISSUE TITLE
Look into how adding link to library captures screenshot

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/phet-edmodo#2]
Currently if an HTML5 sim is added to my edmodo library/favorites it automatically generates a screenshot. Unfortunately this screenshot is of our loading screen...

**Comment by ariel-phet** [comment]
Reproducing the "screenshot" issue when adding a direct link to one of our sims
- In core Edmodo go to "Library"
- Click "Add to Library"
- In pop up click "Link" tab
- In the "http://" input box use the link http://phet.colorado.edu/sims/html/balancing-act/latest/balancing-act_en.html
- Such a link is the direct sim link (instead of the sim page on our website)
- The screenshot displayed by Edmodo will be the "loading" screen of the sim (not the "homescreen" of the sim)

Before we put an "Edmodo This" button on our site we would like to get the screenshot worked out, so that if a teacher has several of our sims in their library it will be easy to distinguish the various resources.

**Comment by ariel-phet** [comment]
Henry will hopefully give us some more information. I told him we are happy to do some work on our end to "ship" a screenshot.

**Comment by ariel-phet** [comment]
From Henry:

>Good news! I checked with the dev that worked on this and I think we can overcome this with some tags added on your end. We grab the image using the [Open Graph protocol](http://ogp.me/). 

>If you manually 'tell us' what image you'd like used for the thumbnail grab (per the instructions at that link), we should be able to use that instead of generating an image on the fly. 

@aaronsamuel137, when time allows it would be great to investigate this issue.

**Comment by ariel-phet** [comment]
@aaronsamuel137 - I can describe a bit more in person.

**Comment by aaronsamuel137** [comment]
I won't plan on working on this until I hear more from you @ariel-phet, since I don't have a clear idea about what any of this is.

**Comment by aaronsamuel137** [comment]
Tested a fix to this with @ariel-phet. Apparently we just need to add one line to our html file:

```html
<meta property="og:image" content="http://phet.colorado.edu/sims/html/[sim name]/latest/[sim-name]-600.png" />
```

I am not sure what the best way to do this is since I haven't worked on the build process as much. Adding developer meeting label to discuss on Tuesday.

**Comment by aaronsamuel137** [comment]
@samreid suggested trying to post a sim on FB now to see if the same screenshot issue occurs there as on edmodo, as well as trying a post with a whole suite of open graph meta tags to see if there might be an advantage to using more besides just the image.

**Comment by samreid** [comment]
From http://ogp.me/

> The Open Graph protocol enables any web page to become a rich object in a social graph. For instance, this is used on Facebook to allow any web page to have the same functionality as any other object on Facebook.

It looks like edmodo is using the same protocol.  Here are other tags we may want to support:

> Basic Metadata
To turn your web pages into graph objects, you need to add basic metadata to your page. We've based the initial version of the protocol on RDFa which means that you'll place additional <meta> tags in the <head> of your web page. The four required properties for every page are:

og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
og:image - An image URL which should represent your object within the graph.
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

**Comment by aaronsamuel137** [comment]
The main concern is to consider how other third parties are interpreting this metadata.

**Comment by pixelzoom** [comment]
Sounds like this involves adding something to chipper/templates/sim.html, and associated build support to fill in new template fields.

Issues:
• Where to point for a screenshot before a sim is published, when a screenshot doesn't yet exist?
• Does title need to be localized?
• Does title need to contain version identifier?

**Comment by pixelzoom** [comment]
For a sim webpage (e.g. acid-base-solutions), we currently have:

```
<meta property="og:title" content="Acid-Base Solutions"/><meta property="og:type" content="phet:simulation"/>
<meta property="og:url" content="http://phet.colorado.edu/en/simulation/acid-base-solutions"/>
<meta property="og:image" content="http://phet.colorado.edu/sims/html/acid-base-solutions/latest/acid-base-solutions-128.png"/>
<meta property="og:site_name" content="PhET"/>
<meta property="og:description" content="How do strong and weak acids differ? Use lab tools on your computer to find out! Dip the paper or the probe into solution to measure the pH, or put in the electrodes to measure the conductivity. Then see how concentration and strength affect pH. Can a weak acid solution have the same pH as a strong acid solution?"/>
```

The ones that are required are title, type, image, url.  These should be added to sim.html.

**Comment by pixelzoom** [comment]
Facebook Open Graph protocol doc: http://ogp.me

**Comment by pixelzoom** [comment]
We're currently missing `og:type`. From the doc:

> og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.

**Comment by pixelzoom** [comment]
This involved:
• added tokens to sim.html, all of which are prefixed with 'OG_'
• replace tokens in createHTMLFiles.js

I'm not quite clear on how to test this. Something about sharing it on my Facebook page, which I'd prefer not to do. @aaronsamuel137 would you mind reviewing and testing that it has the desired result?

**Comment by aaronsamuel137** [comment]
It looks good to me, just one minor fix to add ".html" to the end of the OG_URL.

I've published a new dev version of color vision to test this with, it's at http://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.0-dev.3/color-vision_en.html. @ariel-phet, do you mind testing this with edmodo and see if it works?

**Comment by ariel-phet** [comment]
Appears to be working! Closing.
